spring.application.name=prodotti-service
server.port=${SERVER_PORT:8080}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/prodotti-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
